# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ACEStream ACEStream_Database ACEStream_Decoder ACEStream_Device ACEStream_Document ACEStream_File ACEStream_HTML ACEStream_MediaFramework ACEStream_Miscellaneous ACEStream_Network ACEStream_Network_Protocol_HTTPGet ACEStream_Statistic ACEStream_Visualization)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ACEStream
add_library(ACEStream STATIC IMPORTED)

set_target_properties(ACEStream PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/../../Common/cmake;/mnt/win_d/projects/ACEStream/src/../../Common/src;/mnt/win_d/projects/ACEStream/src/../../Common/src/parser;/mnt/win_d/projects/ACEStream/src/../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/../3rd_party/tree;/mnt/win_d/projects/ACEStream/clang/src/..;/mnt/win_d/projects/ACEStream/src;/mnt/win_d/projects/ACEStream/src/modules/lib;/mnt/win_d/projects/ACEStream/src/modules/misc;/mnt/win_d/projects/ACEStream/src/modules/stat"
)

# Create imported target ACEStream_Database
add_library(ACEStream_Database STATIC IMPORTED)

set_target_properties(ACEStream_Database PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/mysql;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/db/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/db/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/db/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/db/../../../../ACENetwork/src;/mnt/win_d/projects/ACEStream/src/modules/db/../..;/mnt/win_d/projects/ACEStream/src/modules/db/../lib;/mnt/win_d/projects/ACEStream/src/modules/db/../stat"
)

# Create imported target ACEStream_Decoder
add_library(ACEStream_Decoder STATIC IMPORTED)

set_target_properties(ACEStream_Decoder PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/mnt/win_d/projects/ACEStream/src/modules/dec;/usr/include/ImageMagick-6;/usr/include/x86_64-linux-gnu/ImageMagick-6;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/cmake;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src/image;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src/log;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src/parser;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../../Common/src/ui;/mnt/win_d/projects/ACEStream/src/modules/dec/../../../3rd_party/bison;/mnt/win_d/projects/ACEStream/src/modules/dec/../..;/mnt/win_d/projects/ACEStream/src/modules/dec/../dev;/mnt/win_d/projects/ACEStream/src/modules/dec/../lib;/mnt/win_d/projects/ACEStream/src/modules/dec/../vis"
)

# Create imported target ACEStream_Device
add_library(ACEStream_Device STATIC IMPORTED)

set_target_properties(ACEStream_Device PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/gtk-2.0;/usr/lib/x86_64-linux-gnu/gtk-2.0/include;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/fribidi;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/uuid;/usr/include/freetype2;/usr/include/libpng16;/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/dev/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/dev/../../../../Common/src/image;/mnt/win_d/projects/ACEStream/src/modules/dev/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/dev/../vis;/mnt/win_d/projects/ACEStream/src/modules/dev/../..;/mnt/win_d/projects/ACEStream/src/modules/dev/../dec"
)

# Create imported target ACEStream_Document
add_library(ACEStream_Document STATIC IMPORTED)

set_target_properties(ACEStream_Document PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/lib/libreoffice/sdk/include;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/doc/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/doc/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/doc/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/doc/../../../../ACENetwork/src;/mnt/win_d/projects/ACEStream/src/modules/doc/../..;/mnt/win_d/projects/ACEStream/src/modules/doc/../lib;/mnt/win_d/projects/ACEStream/src/modules/doc/../stat"
)

# Create imported target ACEStream_File
add_library(ACEStream_File STATIC IMPORTED)

set_target_properties(ACEStream_File PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/ImageMagick-6;/usr/include/x86_64-linux-gnu/ImageMagick-6;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/file/../../../../Common/cmake;/mnt/win_d/projects/ACEStream/src/modules/file/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/file/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/file/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/file/../..;/mnt/win_d/projects/ACEStream/src/modules/file/../lib"
)

# Create imported target ACEStream_HTML
add_library(ACEStream_HTML STATIC IMPORTED)

set_target_properties(ACEStream_HTML PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/libxml2;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/html/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/html/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/html/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/clang/src/modules/html/../../..;/mnt/win_d/projects/ACEStream/src/modules/html/../..;/mnt/win_d/projects/ACEStream/src/modules/html/../lib"
)

# Create imported target ACEStream_MediaFramework
add_library(ACEStream_MediaFramework STATIC IMPORTED)

set_target_properties(ACEStream_MediaFramework PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/gtk-2.0;/usr/lib/x86_64-linux-gnu/gtk-2.0/include;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/fribidi;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/uuid;/usr/include/freetype2;/usr/include/libpng16;/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/lib/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/lib/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/lib/../../../../Common/src/image;/mnt/win_d/projects/ACEStream/src/modules/lib/../../../../Common/src/log;/mnt/win_d/projects/ACEStream/src/modules/lib/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/lib/../../../../Common/src/ui;/mnt/win_d/projects/ACEStream/src/modules/lib/../..;/mnt/win_d/projects/ACEStream/src/modules/lib/../dec;/mnt/win_d/projects/ACEStream/src/modules/lib/../dev;/mnt/win_d/projects/ACEStream/src/modules/lib"
)

# Create imported target ACEStream_Miscellaneous
add_library(ACEStream_Miscellaneous STATIC IMPORTED)

set_target_properties(ACEStream_Miscellaneous PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src/image;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src/log;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src/parser;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../../Common/src/ui;/mnt/win_d/projects/ACEStream/src/modules/misc/../../../3rd_party/bison;/mnt/win_d/projects/ACEStream/clang/src/modules/misc/../../..;/mnt/win_d/projects/ACEStream/src/modules/misc/../..;/mnt/win_d/projects/ACEStream/src/modules/misc/../dec;/mnt/win_d/projects/ACEStream/src/modules/misc/../dev;/mnt/win_d/projects/ACEStream/src/modules/misc/../file;/mnt/win_d/projects/ACEStream/src/modules/misc/../lib"
)

# Create imported target ACEStream_Network
add_library(ACEStream_Network STATIC IMPORTED)

set_target_properties(ACEStream_Network PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/net/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/net/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/net/../../../../ACENetwork/src;/mnt/win_d/projects/ACEStream/src/modules/net/../../../../ACENetwork/src/client_server;/mnt/win_d/projects/ACEStream/clang/src/modules/net/../../..;/mnt/win_d/projects/ACEStream/src/modules/net/../..;/mnt/win_d/projects/ACEStream/src/modules/net/../lib;/mnt/win_d/projects/ACEStream/src/modules/net/../stat"
)

# Create imported target ACEStream_Network_Protocol_HTTPGet
add_library(ACEStream_Network_Protocol_HTTPGet STATIC IMPORTED)

set_target_properties(ACEStream_Network_Protocol_HTTPGet PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../../../../ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../../../../ACENetwork/src;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../../../../ACENetwork/src/protocol/http;/mnt/win_d/projects/ACEStream/clang/src/modules/net/protocols/http/../../../../..;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../..;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../dec;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../lib;/mnt/win_d/projects/ACEStream/src/modules/net/protocols/http/../../../stat"
)

# Create imported target ACEStream_Statistic
add_library(ACEStream_Statistic STATIC IMPORTED)

set_target_properties(ACEStream_Statistic PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/stat/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/stat/../../../../Common/src/error;/mnt/win_d/projects/ACEStream/src/modules/stat/../../../../Common/src/log;/mnt/win_d/projects/ACEStream/src/modules/stat/../../../../Common/src/math;/mnt/win_d/projects/ACEStream/src/modules/stat/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/stat/../../../../Common/src/ui;/mnt/win_d/projects/ACEStream/clang/src/modules/stat/../../..;/mnt/win_d/projects/ACEStream/src/modules/stat/../..;/mnt/win_d/projects/ACEStream/src/modules/stat/../dev;/mnt/win_d/projects/ACEStream/src/modules/stat/../lib"
)

# Create imported target ACEStream_Visualization
add_library(ACEStream_Visualization STATIC IMPORTED)

set_target_properties(ACEStream_Visualization PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/gtk-2.0;/usr/lib/x86_64-linux-gnu/gtk-2.0/include;/usr/include/pango-1.0;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gdk-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/pango-1.0;/usr/include/harfbuzz;/usr/include/pango-1.0;/usr/include/fribidi;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/uuid;/usr/include/freetype2;/usr/include/libpng16;/media/erik/USB_BLACK/lib/gtkglarea;/usr/include/x86_64-linux-gnu;/usr/include/ImageMagick-6;/usr/include/x86_64-linux-gnu/ImageMagick-6;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/gl;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/image;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/log;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/math;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/timer;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/ui;/mnt/win_d/projects/ACEStream/src/modules/vis/../../../../Common/src/ui/gtk;/mnt/win_d/projects/ACEStream/clang/src/modules/vis/../../..;/mnt/win_d/projects/ACEStream/src/modules/vis/../..;/mnt/win_d/projects/ACEStream/src/modules/vis/../dec;/mnt/win_d/projects/ACEStream/src/modules/vis/../dev;/mnt/win_d/projects/ACEStream/src/modules/vis/../lib;/mnt/win_d/projects/ACEStream/src/modules/vis/../stat"
)

# Import target "ACEStream" for configuration "Debug"
set_property(TARGET ACEStream APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream_Miscellaneous"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/libACEStream.a"
  )

# Import target "ACEStream_Database" for configuration "Debug"
set_property(TARGET ACEStream_Database APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Database PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/db/libACEStream_Database.a"
  )

# Import target "ACEStream_Decoder" for configuration "Debug"
set_property(TARGET ACEStream_Decoder APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Decoder PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "asound;sox;avcodec;avutil;avformat;swscale;/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so;/usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so;Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/dec/libACEStream_Decoder.a"
  )

# Import target "ACEStream_Device" for configuration "Debug"
set_property(TARGET ACEStream_Device APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Device PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "asound;v4l2;ACEStream_Decoder"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/dev/libACEStream_Device.a"
  )

# Import target "ACEStream_Document" for configuration "Debug"
set_property(TARGET ACEStream_Document APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Document PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/doc/libACEStream_Document.a"
  )

# Import target "ACEStream_File" for configuration "Debug"
set_property(TARGET ACEStream_File APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_File PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so;/usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so;/media/erik/USB_BLACK/lib/ACE_TAO/ACE/lib/libACE.so;Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/file/libACEStream_File.a"
  )

# Import target "ACEStream_HTML" for configuration "Debug"
set_property(TARGET ACEStream_HTML APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_HTML PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/html/libACEStream_HTML.a"
  )

# Import target "ACEStream_MediaFramework" for configuration "Debug"
set_property(TARGET ACEStream_MediaFramework APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_MediaFramework PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "X11"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/lib/libACEStream_MediaFramework.a"
  )

# Import target "ACEStream_Miscellaneous" for configuration "Debug"
set_property(TARGET ACEStream_Miscellaneous APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Miscellaneous PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/misc/libACEStream_Miscellaneous.a"
  )

# Import target "ACEStream_Network" for configuration "Debug"
set_property(TARGET ACEStream_Network APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Network PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/net/libACEStream_Network.a"
  )

# Import target "ACEStream_Network_Protocol_HTTPGet" for configuration "Debug"
set_property(TARGET ACEStream_Network_Protocol_HTTPGet APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Network_Protocol_HTTPGet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream;ACEStream_Network"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/net/protocols/http/libACEStream_Network_Protocol_HTTPGet.a"
  )

# Import target "ACEStream_Statistic" for configuration "Debug"
set_property(TARGET ACEStream_Statistic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Statistic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/stat/libACEStream_Statistic.a"
  )

# Import target "ACEStream_Visualization" for configuration "Debug"
set_property(TARGET ACEStream_Visualization APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACEStream_Visualization PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "gmodule-2.0;gthread-2.0;gtk-x11-2.0;gdk-x11-2.0;pangocairo-1.0;atk-1.0;cairo;gdk_pixbuf-2.0;gio-2.0;pangoft2-1.0;pango-1.0;gobject-2.0;glib-2.0;fontconfig;freetype;sox;swscale;avcodec;avutil;/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so;/usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so;/usr/lib/x86_64-linux-gnu/libglut.so.3;/media/erik/USB_BLACK/lib/ACE_TAO/ACE/lib/libACE.so;Common;CommonOpenGL;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACEStream/clang/src/modules/vis/libACEStream_Visualization.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
