set (ESPEAK_NG_SUPPORT_DEFAULT ON)
if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_ESPEAK_NG espeak-ng)
 if (PKG_ESPEAK_NG_FOUND)
  set (ESPEAK_NG_FOUND TRUE)
  set (ESPEAK_NG_INCLUDE_DIRS "${PKG_ESPEAK_NG_INCLUDE_DIRS}")
  set (ESPEAK_NG_LIBRARIES "${PKG_ESPEAK_NG_LIBRARIES}")
 else ()
  set (ESPEAK_NG_LIB_FILE "libespeak-ng.so")
  find_library (ESPEAK_NG_LIBRARY ${ESPEAK_NG__LIB_FILE}
                PATHS /usr
                PATH_SUFFIXES lib64
                DOC "searching for ${ESPEAK_NG_LIB_FILE}")
  if (NOT ESPEAK_NG_LIBRARY)
   message (WARNING "could not find ${ESPEAK_NG_LIB_FILE}, continuing")
  endif (NOT ESPEAK_NG_LIBRARY)
  if (ESPEAK_NG_LIBRARY)
   message (STATUS "Found ${ESPEAK_NG_LIB_FILE} library \"${ESPEAK_NG_LIBRARY}\"")
   set (ESPEAK_NG_FOUND TRUE)
   set (ESPEAK_NG_INCLUDE_DIRS "/usr/include")
   set (ESPEAK_NG_LIBRARIES ${ESPEAK_NG_LIBRARY})
  endif (ESPEAK_NG_LIBRARY) 
 endif (PKG_ESPEAK_NG_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (ESPEAK_NG CONFIG)
  if (ESPEAK_NG_FOUND)
   set (ESPEAK_NG_FOUND TRUE)
   set (ESPEAK_NG_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR_BASE})
   set (ESPEAK_NG_LIB_DIR ${VCPKG_LIB_DIR}/bin)
  endif (ESPEAK_NG_FOUND)
 endif (VCPKG_USE)
 if (NOT ESPEAK_NG_FOUND)
  set (ESPEAK_NG_LIB_FILE "espeak-ng.lib")
  find_library (ESPEAK_NG_LIBRARY ${ESPEAK_NG_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/espeak-ng/build/msvc/src/libespeak-ng
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for ${ESPEAK_NG_LIB_FILE}")
  if (NOT ESPEAK_NG_LIBRARY)
   message (WARNING "could not find ${ESPEAK_NG_LIB_FILE}, continuing")
  endif (NOT ESPEAK_NG_LIBRARY)
  if (ESPEAK_NG_LIBRARY)
   message (STATUS "Found ${ESPEAK_NG_LIB_FILE} library \"${ESPEAK_NG_LIBRARY}\"")
   set (ESPEAK_NG_FOUND TRUE)
   set (ESPEAK_NG_INCLUDE_DIRS "$ENV{LIB_ROOT}/espeak-ng/src/include")
   set (ESPEAK_NG_LIBRARIES ${ESPEAK_NG_LIBRARY})
   set (ESPEAK_NG_LIB_DIR "$ENV{LIB_ROOT}/espeak-ng/build/msvc/src/${CMAKE_BUILD_TYPE}")
  endif (ESPEAK_NG_LIBRARY)
 endif (NOT ESPEAK_NG_FOUND)
endif ()
if (ESPEAK_NG_FOUND)
 option (ESPEAK_NG_SUPPORT "enable espeak-ng support" ${ESPEAK_NG_SUPPORT_DEFAULT})
 if (ESPEAK_NG_SUPPORT)
  add_definitions (-DESPEAK_NG_SUPPORT)
 endif (ESPEAK_NG_SUPPORT)
endif (ESPEAK_NG_FOUND)
