set (MPG123_SUPPORT_DEFAULT ON)
if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_MPG123 libmpg123)
 if (PKG_MPG123_FOUND)
  set (MPG123_FOUND TRUE)
  set (MPG123_INCLUDE_DIRS "${PKG_MPG123_INCLUDE_DIRS}")
  set (MPG123_LIBRARIES "${PKG_MPG123_LIBRARIES}")
 endif (PKG_MPG123_FOUND)
elseif (WIN32)
 if (VCPKG_SUPPORT)
#  cmake_policy (SET CMP0074 OLD)
  find_package (mpg123 CONFIG)
  if (mpg123_FOUND)
   set (MPG123_FOUND TRUE)
   if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR
       CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set (MPG123_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/debug/bin")
   else ()
    set (MPG123_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/bin")
   endif ()
  endif (mpg123_FOUND)
 endif (VCPKG_SUPPORT)
 if (NOT MPG123_FOUND)
#  set (CMAKE_FIND_LIBRARY_SUFFIXES .lib .dll.a)
  set (MPG123_VERSION "1.29.4")
  set (MPG123_DIR "mpg123-${MPG123_VERSION}-x86-64")
#  if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR
#      CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
#   set (MPG123_DIR "${MPG123_DIR}-debug")
#  endif ()
  set (MPG123_LIB_FILE "libmpg123-0")
  find_library (MPG123_LIBRARY
                NAMES ${MPG123_LIB_FILE}
#               PATHS $ENV{LIB_ROOT}/mpg123/src/libmpg123
#               PATH_SUFFIXES .libs
                PATHS $ENV{LIB_ROOT}/mpg123/releases/${MPG123_DIR}
                DOC "searching for ${MPG123_LIB_FILE}"
                NO_DEFAULT_PATH)
  if (NOT MPG123_LIBRARY)
   message (WARNING "could not find ${MPG123_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found mpg123 library \"${MPG123_LIBRARY}\"")
   set (MPG123_FOUND TRUE)
   set (MPG123_INCLUDE_DIRS "$ENV{LIB_ROOT}/mpg123/src/libmpg123")
   set (MPG123_LIBRARIES "${MPG123_LIBRARY}")
#   set (MPG123_LIB_DIR "$ENV{LIB_ROOT}/mpg123/src/libmpg123/.libs")
   set (MPG123_LIB_DIR "$ENV{LIB_ROOT}/mpg123/releases/${MPG123_DIR}")
  endif (NOT MPG123_LIBRARY)
 endif (NOT MPG123_FOUND)
endif ()
if (MPG123_FOUND)
 option (MPG123_SUPPORT "enable mpg123 support" ${MPG123_SUPPORT_DEFAULT})
 if (MPG123_SUPPORT)
  add_definitions (-DMPG123_SUPPORT)
#  include_directories (${MPG123_INCLUDE_DIRS})
 endif (MPG123_SUPPORT)
endif (MPG123_FOUND)
