set (WEBM_SUPPORT_DEFAULT ON)
set (NESTEGG_SUPPORT_DEFAULT ON)
if (UNIX)
# include (FindPkgConfig)
# pkg_check_modules (PKG_WEBM libwebm)
# if (PKG_WEBM_FOUND)
#  set (WEBM_FOUND TRUE)
#  set (WEBM_INCLUDE_DIRS "${PKG_WEBM_INCLUDE_DIRS}")
#  set (WEBM_LIBRARIES "${PKG_WEBM_LIBRARIES}")
# endif (PKG_WEBM_FOUND)
 set (WEBM_LIB_FILE "libwebm.a")
 find_library (WEBM_LIBRARY
               NAMES ${WEBM_LIB_FILE}
               PATHS $ENV{LIB_ROOT}/libwebm/build_/gcc
               PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
               DOC "searching for ${WEBM_LIB_FILE}"
               NO_DEFAULT_PATH)
 if (NOT WEBM_LIBRARY)
  message (WARNING "could not find ${WEBM_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found webm library \"${WEBM_LIBRARY}\"")
  set (WEBM_FOUND TRUE)
  set (WEBM_INCLUDE_DIRS "$ENV{LIB_ROOT}/libwebm;$ENV{LIB_ROOT}/libwebm/webm_parser/include")
  set (WEBM_LIBRARIES "${WEBM_LIBRARY}")
#  set (WEBM_LIB_DIR "$ENV{LIB_ROOT}/libwebm/build_/gcc/${CMAKE_BUILD_TYPE}")
 endif (NOT WEBM_LIBRARY)
 pkg_check_modules (PKG_NESTEGG nestegg)
 if (PKG_NESTEGG_FOUND)
  set (NESTEGG_FOUND TRUE)
  set (NESTEGG_INCLUDE_DIRS "${PKG_NESTEGG_INCLUDE_DIRS}")
  set (NESTEGG_LIBRARIES "${PKG_NESTEGG_LIBRARIES}")
 endif (PKG_NESTEGG_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (libwebm CONFIG)
  if (libwebm_FOUND)
   set (WEBM_FOUND TRUE)
   set (WEBM_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR})
   set (WEBM_LIBRARIES "${VCPKG_LIB_DIR}/webm.lib")
   set (WEBM_LIB_DIR ${VCPKG_BIN_DIR})
  endif (libwebm_FOUND)
  find_package (nestegg CONFIG)
  if (nestegg_FOUND)
   set (NESTEGG_FOUND TRUE)
   set (NESTEGG_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR})
   set (NESTEGG_LIBRARIES "${VCPKG_LIB_DIR}/nestegg.lib")
   set (NESTEGG_LIB_DIR ${VCPKG_BIN_DIR})
  endif (nestegg_FOUND)
 endif (VCPKG_USE)
 if (NOT WEBM_FOUND)
  set (WEBM_LIB_FILE "webm.lib")
  find_library (WEBM_LIBRARY
                NAMES ${WEBM_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/libwebm/build_/msvc
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for ${WEBM_LIB_FILE}"
                NO_DEFAULT_PATH)
  if (NOT WEBM_LIBRARY)
   message (WARNING "could not find ${WEBM_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found webm library \"${WEBM_LIBRARY}\"")
   set (WEBM_FOUND TRUE)
   set (WEBM_INCLUDE_DIRS "$ENV{LIB_ROOT}/libwebm;$ENV{LIB_ROOT}/libwebm/webm_parser/include")
   set (WEBM_LIBRARIES "${WEBM_LIBRARY}")
   set (WEBM_LIB_DIR "$ENV{LIB_ROOT}/libwebm/build_/msvc/${CMAKE_BUILD_TYPE}")
  endif (NOT WEBM_LIBRARY)
 endif (NOT WEBM_FOUND)
 if (NOT NESTEGG_FOUND)
  set (NESTEGG_LIB_FILE "libnestegg.dll.a")
  find_library (NESTEGG_LIBRARY
                NAMES ${NESTEGG_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/nestegg/src
                PATH_SUFFIXES .libs
                DOC "searching for ${NESTEGG_LIB_FILE}"
                NO_DEFAULT_PATH)
  if (NOT NESTEGG_LIBRARY)
   message (WARNING "could not find ${NESTEGG_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found nestegg library \"${NESTEGG_LIBRARY}\"")
   set (NESTEGG_FOUND TRUE)
   set (NESTEGG_INCLUDE_DIRS "$ENV{LIB_ROOT}/nestegg/include")
   set (NESTEGG_LIBRARIES "${NESTEGG_LIBRARY}")
   set (NESTEGG_LIB_DIR "$ENV{LIB_ROOT}/nestegg/src/.libs")
  endif (NOT NESTEGG_LIBRARY)
 endif (NOT NESTEGG_FOUND)
endif ()
if (WEBM_FOUND)
 option (WEBM_SUPPORT "enable libwebm support" ${WEBM_SUPPORT_DEFAULT})
 if (WEBM_SUPPORT)
  add_definitions (-DWEBM_SUPPORT)
 endif (WEBM_SUPPORT)
endif (WEBM_FOUND)
if (NESTEGG_FOUND)
 option (NESTEGG_SUPPORT "enable nestegg support" ${NESTEGG_SUPPORT_DEFAULT})
 if (NESTEGG_SUPPORT)
  add_definitions (-DNESTEGG_SUPPORT)
 endif (NESTEGG_SUPPORT)
endif (NESTEGG_FOUND)
