set (WEBM_SUPPORT_DEFAULT ON)
if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_NESTEGG nestegg)
 if (PKG_NESTEGG_FOUND)
  set (WEBM_FOUND TRUE)
  set (WEBM_INCLUDE_DIRS "${PKG_NESTEGG_INCLUDE_DIRS}")
  set (WEBM_LIBRARIES "${PKG_NESTEGG_LIBRARIES}")
endif (PKG_NESTEGG_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (nestegg CONFIG)
  if (nestegg_FOUND)
   set (WEBM_FOUND TRUE)
   set (WEBM_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR})
   set (WEBM_LIBRARIES "${VCPKG_LIB_DIR}/nestegg.lib")
   set (WEBM_LIB_DIR ${VCPKG_BIN_DIR})
  endif (nestegg_FOUND)
 endif (VCPKG_USE)
 if (NOT nestegg_FOUND)
  set (NESTEGG_LIB_FILE "libnestegg.dll.a")
  find_library (NESTEGG_LIBRARY
                NAMES ${NESTEGG_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/nestegg/src
                PATH_SUFFIXES .libs
                DOC "searching for ${NESTEGG_LIB_FILE}"
                NO_DEFAULT_PATH)
  if (NOT NESTEGG_LIBRARY)
   message (WARNING "could not find ${NESTEGG_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found webm library \"${NESTEGG_LIBRARY}\"")
   set (WEBM_FOUND TRUE)
   set (WEBM_INCLUDE_DIRS "$ENV{LIB_ROOT}/nestegg/include")
   set (WEBM_LIBRARIES "${NESTEGG_LIBRARY}")
   set (WEBM_LIB_DIR "$ENV{LIB_ROOT}/nestegg/src/.libs")
  endif (NOT NESTEGG_LIBRARY)
 endif (NOT WEBM_FOUND)
endif ()
if (WEBM_FOUND)
 option (WEBM_SUPPORT "enable webm support" ${WEBM_SUPPORT_DEFAULT})
 if (WEBM_SUPPORT)
  add_definitions (-DWEBM_SUPPORT)
 endif (WEBM_SUPPORT)
endif (WEBM_FOUND)
