set (WHISPERCPP_SUPPORT_DEFAULT ON)
if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_WHISPERCPP whisper.cpp)
 if (PKG_WHISPERCPP_FOUND)
  set (WHISPERCPP_FOUND TRUE)
  set (WHISPERCPP_INCLUDE_DIRS "${PKG_WHISPERCPP_INCLUDE_DIRS}")
  set (WHISPERCPP_LIBRARIES "${PKG_WHISPERCPP_LIBRARIES}")
 else ()
  set (WHISPERCPP_LIB_FILE "libwhisper.so")
  find_library (WHISPERCPP_LIBRARY ${WHISPERCPP_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/whisper.cpp/build/gcc/src
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for ${WHISPERCPP_LIB_FILE}")
  if (NOT WHISPERCPP_LIBRARY)
   message (WARNING "could not find ${WHISPERCPP_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found ${WHISPERCPP_LIB_FILE} library \"${WHISPERCPP_LIBRARY}\"")
   set (WHISPERCPP_FOUND TRUE)
   set (WHISPERCPP_INCLUDE_DIRS "$ENV{LIB_ROOT}/whisper.cpp/ggml/include;$ENV{LIB_ROOT}/whisper.cpp/include")
   set (WHISPERCPP_LIBRARIES "${WHISPERCPP_LIBRARY}")
  endif (NOT WHISPERCPP_LIBRARY)
 endif (PKG_WHISPERCPP_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
  find_package (whisper.cpp CONFIG)
  if (WHISPER.CPP_FOUND)
   set (WHISPERCPP_FOUND TRUE)
   set (WHISPERCPP_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR_BASE})
   set (WHISPERCPP_LIB_DIR ${VCPKG_LIB_DIR}/bin)
  endif (WHISPER.CPP_FOUND)
 endif (VCPKG_USE)
 if (NOT WHISPERCPP_FOUND)
  set (WHISPERCPP_LIB_FILE "whisper.lib")
  find_library (WHISPERCPP_LIBRARY ${WHISPERCPP_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/whisper.cpp/build/msvc/src
#                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for ${WHISPERCPP_LIB_FILE}"
                NO_DEFAULT_PATH)
  if (NOT WHISPERCPP_LIBRARY)
   message (WARNING "could not find ${WHISPERCPP_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found ${WHISPERCPP_LIB_FILE} library \"${WHISPERCPP_LIBRARY}\"")
   set (WHISPERCPP_FOUND TRUE)
   set (WHISPERCPP_INCLUDE_DIRS "$ENV{LIB_ROOT}/whisper.cpp/ggml/include;$ENV{LIB_ROOT}/whisper.cpp/include")
   set (WHISPERCPP_LIBRARIES "${WHISPERCPP_LIBRARY}")
#   set (WHISPERCPP_LIB_DIRS "$ENV{ROCM_PATH}/bin;$ENV{LIB_ROOT}/whisper.cpp/build/msvc/bin/${CMAKE_BUILD_TYPE}")
   set (WHISPERCPP_LIB_DIRS "$ENV{ROCM_PATH}/bin;$ENV{LIB_ROOT}/whisper.cpp/build/msvc/bin")
  endif (NOT WHISPERCPP_LIBRARY)
 endif (NOT WHISPERCPP_FOUND)
endif ()
if (WHISPERCPP_FOUND)
 option (WHISPERCPP_SUPPORT "enable whisper.cpp support" ${WHISPERCPP_SUPPORT_DEFAULT})
 if (WHISPERCPP_SUPPORT)
  add_definitions (-DWHISPERCPP_SUPPORT)
 endif (WHISPERCPP_SUPPORT)
endif (WHISPERCPP_FOUND)
