set (ZLIB_SUPPORT_DEFAULT ON)
if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_ZLIB zlib)
 if (PKG_ZLIB_FOUND)
  set (ZLIB_FOUND TRUE)
  set (ZLIB_INCLUDE_DIRS "${PKG_ZLIB_INCLUDE_DIRS}")
  set (ZLIB_LIBRARIES "${PKG_ZLIB_LIBRARIES}")
 endif (PKG_ZLIB_FOUND)
elseif (WIN32)
 if (VCPKG_SUPPORT)
#  cmake_policy (SET CMP0074 OLD)
  find_package (zlib CONFIG)
  if (zlib_FOUND)
   set (ZLIB_FOUND TRUE)
   if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR
       CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set (ZLIB_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/debug/bin")
   else ()
    set (ZLIB_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/bin")
   endif ()
  endif (zlib_FOUND)
 else ()
  set (ZLIB_LIB_FILE "opencv_core${OPENCV_VERSION}${LIB_FILE_SUFFIX}.lib")
  find_library (ZLIB_LIBRARY ${ZLIB_LIB_FILE}
                PATHS $ENV{LIB_ROOT}/zlib/cmake
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for ${ZLIB_CORE_LIB_FILE}"
                NO_DEFAULT_PATH)
  if (NOT ZLIB_LIBRARY)
   message (WARNING "could not find ${ZLIB_LIB_FILE}, continuing")
  else ()
   message (STATUS "Found ${ZLIB_FILE} library \"${ZLIB_LIBRARY}\"")
   set (ZLIB_FOUND TRUE)
   set (ZLIB_INCLUDE_DIRS "$ENV{LIB_ROOT}/zlib;$ENV{LIB_ROOT}/zlib/cmake")
   set (ZLIB_LIBRARIES "${ZLIB_LIBRARY}")
   set (ZLIB_LIB_DIR "$ENV{LIB_ROOT}/zlib/cmake/${CMAKE_BUILD_TYPE}")
  endif (NOT ZLIB_LIBRARY)
 endif (VCPKG_SUPPORT)
endif ()
if (ZLIB_FOUND)
 option (ZLIB_SUPPORT "enable zlib support" ${ZLIB_SUPPORT_DEFAULT})
 if (ZLIB_SUPPORT)
  add_definitions (-DZLIB_SUPPORT)
#  include_directories (${ZLIB_INCLUDE_DIRS})
 endif (ZLIB_SUPPORT)
endif (ZLIB_FOUND)
