
if (UNIX)
 set (CPACK_CMAKE_GENERATOR "Unix Makefiles")

 set (CPACK_GENERATOR "STGZ;TGZ;TZ")
endif ()

set (CPACK_INSTALL_CMAKE_PROJECTS "release;ACStream;ALL;/")

set (CPACK_NSIS_DISPLAY_NAME "ACEStream")

set (CPACK_OUTPUT_CONFIG_FILE "release/CPackConfig.cmake")

set (CPACK_PACKAGE_DESCRIPTION_FILE "README")
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "ACEStream is a streaming library")
set (CPACK_PACKAGE_EXECUTABLES "camsource;camtarget")
set (CPACK_PACKAGE_FILE_NAME "camstream")
set (CPACK_PACKAGE_INSTALL_DIRECTORY "ACEStream/camstream")
set (CPACK_PACKAGE_INSTALL_REGISTRY_KEY "ACEStream")
set (CPACK_PACKAGE_NAME "ACEStream")
set (CPACK_PACKAGE_VENDOR "")
set (CPACK_PACKAGE_VERSION "0.1")
set (CPACK_PACKAGE_VERSION_MAJOR "0")
set (CPACK_PACKAGE_VERSION_MINOR "1")
set (CPACK_PACKAGE_VERSION_PATCH "0")

set (CPACK_RESOURCE_FILE_LICENSE "LICENSE")
set (CPACK_RESOURCE_FILE_README "README")
set (CPACK_RESOURCE_FILE_WELCOME "")

if (UNIX)
set (CPACK_SOURCE_GENERATOR "TGZ;TZ")
endif ()

set (CPACK_SOURCE_OUTPUT_CONFIG_FILE "release/CPackSourceConfig.cmake")
set (CPACK_SOURCE_PACKAGE_FILE_NAME "ACEStream-0.1.0")
set (CPACK_SOURCE_STRIP_FILES "")

set (CPACK_STRIP_FILES "bin/camsource;bin/camtarget")

if (UNIX)
set (CPACK_SYSTEM_NAME "Linux-i686")

set (CPACK_TOPLEVEL_TAG "Linux-i686")
endif ()

