name: 'install_deps'
description: 'install package dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - run: sudo apt-get update
    shell: bash
  - run: sudo apt-get install -y libmysqlclient-dev libsox-dev libmpg123-dev libasound2-dev libv4l-dev libreoffice-dev freeglut3-dev
    shell: bash
#    if: inputs.os == 'ubuntu-latest'
#  - run:
#    shell: bash
#    if: inputs.os == 'windows-latest'
#  - run:
#   shell: bash
#   if: inputs.os == 'macos-latest'

