name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v11
    with:
     vcpkgDirectory: '${{ env.VCPKG_ROOT }}'
     vcpkgGitCommitId: '099fb9250d916511782bf5215f01f2e7141beb3a'
     runVcpkgInstall: true
     vcpkgJsonGlob: '**/vcpkg.json'
     appendedCacheKey: vcpkginstall

  - run: choco install libreoffice-fresh
    shell: cmd
