name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v11
    with:
     vcpkgDirectory: '${{ env.VCPKG_ROOT }}'
     vcpkgGitCommitId: 'a0400024711b283056538ac19ced80b91a83c24c'
     runVcpkgInstall: true
     vcpkgJsonGlob: '**/vcpkg.json'
     doNotCache: false

  - run: choco install libreoffice-fresh libreoffice-sdk
    shell: cmd
