name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v10
    with:
     vcpkgDirectory: '${{ env.VCPKG_ROOT }}'
     vcpkgGitCommitId: '30a20e8f15ff26eec665205dea52f4ffc6f0814b'
     # Run vcpkg with the command specified by the `runVcpkgFormatString` input
     runVcpkgInstall: true
     vcpkgJsonGlob: '**/vcpkg.json'
     #vcpkgJsonGlob: '${{ runner.workspace }}/a/ACEStream/vcpkg.json'
     appendedCacheKey: vcpkginstall

  - run: choco install libreoffice-fresh
    shell: cmd
