name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v10
    with:
     vcpkgGitCommitId: '30a20e8f15ff26eec665205dea52f4ffc6f0814b'
  - run: |
         vcpkg update
         vcpkg install assimp:x64-windows ffmpeg:x64-windows freeglut:x64-windows glm:x64-windows graphicsmagick:x64-windows gtk:x64-windows
    shell: cmd
