#ifndef STREAM_MODULE_DB_DEFINES_H
#define STREAM_MODULE_DB_DEFINES_H

#define MODULE_DB_MYSQL_TARGET_DEFAULT_NAME_STRING "MySQLTarget"

#define MODULE_DB_MYSQL_DEFAULT_CHARACTER_SET      "utf8"
#define MODULE_DB_MYSQL_DEFAULT_PORT               3306
#define MODULE_DB_MYSQL_DEFAULT_TIMEOUT_CONNECT    3 // seconds
#define MODULE_DB_MYSQL_DEFAULT_TIMEOUT_READ       3 // seconds
#define MODULE_DB_MYSQL_DEFAULT_TIMEOUT_WRITE      3 // seconds
#define MODULE_DB_MYSQL_DEFAULT_RECONNECT          true
#define MODULE_DB_MYSQL_DEFAULT_USER               "root"

#endif
