name: 'install_Common'
description: 'install library dependencies on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: actions/checkout@v1
    with:
     repository: esohns/Common
#     token: ${{ secrets.ACCESS_TOKEN }}

