// -*- C++ -*-
//
// generated by wxGlade 0.8.3 on Fri Jan  4 23:13:58 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CAMSAVE_WXWIDGETS_UI_H
#define CAMSAVE_WXWIDGETS_UI_H

#undef DrawText
#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/statline.h>
#include <wx/tglbtn.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class wxDialog_main: public wxDialog {
public:
  // begin wxGlade: wxDialog_main::ids
  // end wxGlade

  wxDialog_main(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
  // begin wxGlade: wxDialog_main::attributes
  wxToggleButton* togglebutton_record;
  wxButton* button_snapshot;
  wxButton* button_cut;
  wxButton* button_report;
  wxSpinCtrl* spinctrl_control;
  wxSpinCtrl* spinctrl_session;
  wxSpinCtrl* spinctrl_data;
  wxSpinCtrl* spinctrl_payload;
  wxSpinCtrl* spinctrl_framesize;
  wxButton* button_reset_camera;
  wxChoice* choice_source;
  wxButton* button_camera_properties;
  wxChoice* choice_format;
  wxChoice* choice_resolution;
  wxChoice* choice_framerate;
  wxToggleButton* togglebutton_display;
  wxToggleButton* togglebutton_fullscreen;
  wxChoice* choice_displayadapter;
  wxChoice* choice_screen;
  wxChoice* choice_resolution_2;
  wxToggleButton* togglebutton_save;
  wxTextCtrl* textctrl_filename;
  wxPanel* panel_video;
  wxGauge* gauge_progress;
  wxButton* button_about;
  wxButton* button_quit;
  // end wxGlade

  DECLARE_EVENT_TABLE();

public:
  virtual void dialog_main_idle_cb (wxIdleEvent&) = 0;
  virtual void dialog_main_keydown_cb (wxKeyEvent&) = 0;
  virtual void togglebutton_record_toggled_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_snapshot_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_cut_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_report_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_reset_camera_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_source_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_camera_properties_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_format_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_resolution_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_framerate_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void togglebutton_display_toggled_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void togglebutton_fullscreen_toggled_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_displayadapter_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_screen_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void choice_resolution_2_changed_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void togglebutton_save_toggled_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_about_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
  virtual void button_quit_clicked_cb(wxCommandEvent &event) = 0; // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // CAMSAVE_WXWIDGETS_UI_H
