#ifndef STREAM_MODULE_MISC_DEFINES_H
#define STREAM_MODULE_MISC_DEFINES_H

#if defined (ACE_WIN32) || defined (ACE_WIN64)
#define MODULE_MISC_DS_WIN32_FILTER_NAME_SOURCE L"ACEStream Source"
#endif

#endif
