#ifndef STREAM_MODULE_ML_DEFINES_H
#define STREAM_MODULE_ML_DEFINES_H

#define MODULE_ML_TENSORFLOW_DEFAULT_NAME_STRING         "Tensorflow"
#define MODULE_ML_LIBTORCH_DEFAULT_NAME_STRING           "Libtorch"

#define MODULE_ML_LLAMA_CPP_DEFAULT_NAME_STRING          "LlamaCpp"
#define MODULE_ML_LLAMA_CPP_DEFAULT_CONTEXT_SIZE         131072
#define MODULE_ML_LLAMA_CPP_DEFAULT_NUMBER_OF_GPU_LAYERS 99

#endif
