#ifndef STREAM_MODULE_ML_DEFINES_H
#define STREAM_MODULE_ML_DEFINES_H

#define MODULE_ML_TENSORFLOW_DEFAULT_NAME_STRING "Tensorflow"
#define MODULE_ML_LIBTORCH_DEFAULT_NAME_STRING   "Libtorch"

#endif
