if (WIN32)
 if (VCPKG_USE)
  find_package (directx-headers CONFIG)
  if (directx-headers_FOUND)
   message (STATUS "found vcpkg directx-headers")
   set (DIRECTX_HEADERS_FOUND TRUE)
   set (DIRECTX_HEADERS_INCLUDE_DIR ${VCPKG_INCLUDE_DIR}/directx)
   set (DIRECTX_HEADERS_LIBRARIES ${VCPKG_LIB_DIR}/DirectX-Guids.lib;${VCPKG_LIB_DIR}/DirectX-Headers.lib)
  endif (directx-headers_FOUND)
 endif (VCPKG_USE)
 if (NOT DIRECTX_HEADERS_FOUND)
  find_library (DIRECTX_HEADERS_LIBRARY DirectX-Headers.lib
                PATHS $ENV{VCPKG_INSTALLATION_ROOT}/installed/x64-windows
                PATH_SUFFIXES lib
                DOC "searching for DirectX-Headers.lib"
                NO_DEFAULT_PATH)
  if (NOT DIRECTX_HEADERS_LIBRARY)
   message (FATAL_ERROR "could not find DirectX-Headers.lib, continuing")
  else ()
   message (STATUS "found DirectX-Headers.lib library \"${DIRECTX_HEADERS_LIBRARY}\"")
  endif (NOT DIRECTX_HEADERS_LIBRARY)
  if (DIRECTX_HEADERS_LIBRARY)
   set (DIRECTX_HEADERS_FOUND TRUE)
   set (DIRECTX_HEADERS_INCLUDE_DIR $ENV{VCPKG_INSTALLATION_ROOT}/installed/x64-windows/include/directx)
   set (DIRECTXSDK_LIBRARIES ${DIRECTX_HEADERS_LIBRARY})
  endif (DIRECTX_HEADERS_LIBRARY)
 endif (NOT DIRECTX_HEADERS_FOUND)
endif (WIN32)
if (DIRECTX_HEADERS_FOUND)
 option (DIRECTX_HEADERS_SUPPORT "enable DirectX headers support" ON)
 if (DIRECTX_HEADERS_SUPPORT)
  add_definitions (-DDIRECTX_HEADERS_SUPPORT)
 endif (DIRECTX_HEADERS_SUPPORT)
endif (DIRECTX_HEADERS_FOUND)
