set (X11_SUPPORT_DEFAULT ON)
if (UNIX)
 include (FindPkgConfig)
 pkg_check_modules (PKG_X11 x11)
 if (PKG_X11_FOUND)
  set (X11_FOUND TRUE)
  set (X11_INCLUDE_DIRS "${PKG_X11_INCLUDE_DIRS}")
  set (X11_LIBRARIES "${PKG_X11_LIBRARIES}")
 endif (PKG_X11_FOUND)
endif (UNIX)
if (X11_FOUND)
 option (X11_SUPPORT "enable X11 support" ${X11_SUPPORT_DEFAULT})
 if (X11_SUPPORT)
  add_definitions (-DX11_SUPPORT)
 endif (X11_SUPPORT)
endif (X11_FOUND)
