// -*- C++ -*-
//
// generated by wxGlade 0.8.3 on Fri Jan  4 23:13:58 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "avsave_wxwidgets_ui.h"

// begin wxGlade: ::extracode
// end wxGlade



wxDialog_main::wxDialog_main(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
  wxDialog(parent, id, title, pos, size, wxCAPTION|wxDIALOG_NO_PARENT|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
}

BEGIN_EVENT_TABLE(wxDialog_main, wxDialog)
  EVT_IDLE (wxDialog_main::dialog_main_idle_cb)
  EVT_CHAR_HOOK (wxDialog_main::dialog_main_keydown_cb)
// begin wxGlade: wxDialog_main::event_table
  EVT_TOGGLEBUTTON(wxID_ANY, wxDialog_main::togglebutton_record_toggled_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_snapshot_clicked_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_cut_clicked_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_report_clicked_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_reset_camera_clicked_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_source_changed_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_camera_properties_clicked_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_format_changed_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_resolution_changed_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_framerate_changed_cb)
  EVT_TOGGLEBUTTON(wxID_ANY, wxDialog_main::togglebutton_display_toggled_cb)
  EVT_TOGGLEBUTTON(wxID_ANY, wxDialog_main::togglebutton_fullscreen_toggled_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_displayadapter_changed_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_screen_changed_cb)
  EVT_CHOICE(wxID_ANY, wxDialog_main::choice_resolution_2_changed_cb)
  EVT_TOGGLEBUTTON(wxID_ANY, wxDialog_main::togglebutton_save_toggled_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_about_clicked_cb)
  EVT_BUTTON(wxID_ANY, wxDialog_main::button_quit_clicked_cb)
  // end wxGlade
END_EVENT_TABLE();
