set (OPENAL_SUPPORT_DEFAULT ON)
if (UNIX)
 pkg_check_modules (PKG_OPENAL openal)
 if (PKG_OPENAL_FOUND)
  set (OPENAL_FOUND TRUE)
  set (OPENAL_INCLUDE_DIRS "${PKG_OPENAL_INCLUDE_DIRS}")
  set (OPENAL_LIBRARIES "${PKG_OPENAL_LIBRARIES}")
 else ()
  find_library (OPENAL_LIBRARY libopenal.so
                PATHS /usr/local
                PATH_SUFFIXES lib64
                DOC "searching for libopenal.so"
                NO_DEFAULT_PATH)
  if (OPENAL_LIBRARY)
   set (OPENAL_FOUND TRUE)
   set (OPENAL_INCLUDE_DIRS "/usr/local/include/libopenal")
   set (OPENAL_LIBRARIES "${OPENAL_LIBRARY}")
  endif (OPENAL_LIBRARY)
 endif (PKG_OPENAL_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
#  cmake_policy (SET CMP0074 OLD)
  find_package (libopenal CONFIG)
  if (libopenal_FOUND)
   set (OPENAL_FOUND TRUE)
   set (OPENAL_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR})
#   set (OPENAL_LIBRARIES "${libopenal_LIBRARIES}")
   set (OPENAL_LIB_DIR ${VCPKG_BIN_DIR})
  endif (libopenal_FOUND)
 endif (VCPKG_USE)
 if (NOT OPENAL_FOUND)
  find_library (OPENAL_LIBRARY OpenAL32.lib
                PATHS $ENV{LIB_ROOT}/openal/libs
                PATH_SUFFIXES Win64
                DOC "searching for OpenAL32.lib"
                NO_DEFAULT_PATH)
  if (NOT OPENAL_LIBRARY)
   message (WARNING "could not find OpenAL32.lib, continuing")
  else ()
   message (STATUS "Found OpenAL32.lib library \"${OPENAL_LIBRARY}\"")
   set (OPENAL_FOUND TRUE)
   set (OPENAL_INCLUDE_DIRS "$ENV{LIB_ROOT}/openal/include")
   set (OPENAL_LIBRARIES "${OPENAL_LIBRARY}")
   set (OPENAL_LIB_DIR "$ENV{LIB_ROOT}/openal/libs/Win64")
  endif (NOT OPENAL_LIBRARY)
 endif (NOT OPENAL_FOUND)
endif ()
if (OPENAL_FOUND)
 option (OPENAL_SUPPORT "enable OpenAL support" ${OPENAL_SUPPORT_DEFAULT})
 if (OPENAL_SUPPORT)
  add_definitions (-DOPENAL_SUPPORT)
#  include_directories (${OPENAL_INCLUDE_DIRS})
 endif (OPENAL_SUPPORT)
endif (OPENAL_FOUND)
