name: 'install_ACE_win32'
description: 'install ACE on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - run: vcpkg --vcpkg-root=${{env.VCPKG_ROOT}} install ace[ssl,xml]:x64-windows
    shell: cmd
