name: 'install_ACE_win32'
description: 'install ACE on the runner'
inputs:
 os:  # id of input
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v10
    with:
     vcpkgDirectory: '${{github.workspace}}/vcpkg'
     vcpkgGitCommitId: '973a7d517c09c8cfb7e6a548fcc260ca34ba7b60'
  - run: vcpkg install ace[ssl,xml]:x64-windows
    shell: cmd
